# Generated by Django 5.1.15 on 2026-09-28 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome da Tecnologia')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (Identificador)')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='Ícone / Sigla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Feed')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título da Pílula')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Resumo do Código')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Arquivo de Vídeo (9:16 MP4/WebM)')),
                ('duration_seconds', models.PositiveIntegerField(default=30, verbose_name='Duração em Segundos')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado no Feed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Autor / Criador')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='videos.technology', verbose_name='Tecnologia Principal')),
            ],
            options={
                'verbose_name': 'Micro-Vídeo',
                'verbose_name_plural': 'Micro-Vídeos',
                'ordering': ['-created_at'],
            },
        ),
    ]
